# Generated by Django 5.0.7 on 2024-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='tx_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='tx_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
