# Generated by Django 5.0.7 on 2024-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verify_app', '0002_claim_tx_status_claim_tx_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ipfs_hash_dep',
            field=models.CharField(default='', max_length=255),
        ),
    ]
